# Generated by Django 3.2.16 on 2022-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221108_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='memmory',
            field=models.CharField(max_length=120),
        ),
    ]
